
version: '3.9'
services:
  disaster-bot:
    build: .
    container_name: disaster-event-chatbot
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - DB_PATH=/app/data/events.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
